/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.theoretics;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Theoretics
 */
public class ParkingPanel extends javax.swing.JFrame {

    private int width;
    private int height;
    /**
     * Creates new form ParkingPanel
     */
    public ParkingPanel() {
        setUndecorated(true);
        
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        //Dimension frameSize = getSize();
        width = screenSize.width - 150;
        height = screenSize.height - 180;
        
        BG.setSize(new Dimension(screenSize.width, screenSize.height));
        centerPanel.setSize(new Dimension(screenSize.width, screenSize.height));
        BG.setIcon(new ImageIcon(new ImageIcon(getClass()
                .getResource("/com/resources/TIEFighter.png"))
                .getImage()
                .getScaledInstance(screenSize.width, screenSize.height, Image.SCALE_DEFAULT)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enteringLabel = new javax.swing.JLabel();
        exitingLabel = new javax.swing.JLabel();
        sysMsg1 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(480, 320));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        northPanel.setBackground(new java.awt.Color(0, 0, 0));
        northPanel.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("PARKING QUEUE MANAGEMENT  .::.  THEORETICS INC");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        northPanel.add(jLabel1);

        getContentPane().add(northPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 30));

        centerPanel.setBackground(new java.awt.Color(0, 0, 0));
        centerPanel.setOpaque(false);
        centerPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        centerPanel.setLayout(new java.awt.GridLayout(3, 4, 0, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Entering");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        centerPanel.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Exiting");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        centerPanel.add(jLabel3);

        enteringLabel.setFont(new java.awt.Font("SansSerif", 1, 150)); // NOI18N
        enteringLabel.setForeground(new java.awt.Color(0, 255, 0));
        enteringLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enteringLabel.setText("0");
        enteringLabel.setMinimumSize(new java.awt.Dimension(67, 200));
        enteringLabel.setPreferredSize(new java.awt.Dimension(67, 200));
        centerPanel.add(enteringLabel);

        exitingLabel.setFont(new java.awt.Font("SansSerif", 1, 150)); // NOI18N
        exitingLabel.setForeground(new java.awt.Color(255, 255, 0));
        exitingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitingLabel.setText("0");
        exitingLabel.setMinimumSize(new java.awt.Dimension(67, 200));
        exitingLabel.setPreferredSize(new java.awt.Dimension(67, 200));
        centerPanel.add(exitingLabel);

        getContentPane().add(centerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, 500, 540));

        sysMsg1.setForeground(new java.awt.Color(0, 255, 255));
        sysMsg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sysMsg1.setText("system");
        sysMsg1.setPreferredSize(new java.awt.Dimension(480, 15));
        getContentPane().add(sysMsg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/TIEFighter.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParkingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParkingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParkingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParkingPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParkingPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JPanel centerPanel;
    public javax.swing.JLabel enteringLabel;
    public javax.swing.JLabel exitingLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel northPanel;
    public javax.swing.JLabel sysMsg1;
    // End of variables declaration//GEN-END:variables
}
